const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 800,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
  },
  {
    title: "Cultural Hideaway in Kyoto",
    description: "Immerse yourself in Japanese culture in this tranquil Kyoto retreat, surrounded by temples and gardens.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1553514029-1318c9127859?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Kyoto",
    country: "Japan",
  },
  {
    title: "Desert Dome Stay",
    description: "Experience the desert like never before in this unique geodesic dome with breathtaking night skies.",
    image: { 
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1100,
    location: "Joshua Tree",
    country: "United States",
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to this quaint English countryside cottage surrounded by rolling green hills.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1300,
    location: "Cotswolds",
    country: "United Kingdom",
  },
  {
    title: "Island Bungalow",
    description: "Wake up to the sound of waves in this tropical overwater bungalow in the Maldives.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1572211213458-0d4f5c4eb7a4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Malé",
    country: "Maldives",
  },
  {
    title: "Clifftop Villa",
    description: "Watch the sunset over the Mediterranean from this luxurious clifftop villa.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1582719478148-c89cae4dc85b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2800,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Modern Scandinavian Home",
    description: "Sleek, minimal design and cozy interiors await in this Nordic getaway.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Stockholm",
    country: "Sweden",
  },
  {
    title: "Jungle Eco Lodge",
    description: "Stay in harmony with nature in this sustainable jungle eco-lodge.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1519821172141-b5d8b1e1f38e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1400,
    location: "Ubud",
    country: "Indonesia",
  },
  {
    title: "Countryside Farm Stay",
    description: "Reconnect with the land and animals at this peaceful countryside farm.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 950,
    location: "Nashville",
    country: "United States",
  },
  {
    title: "Elegant Parisian Apartment",
    description: "Sip coffee on the balcony and watch the Parisian streets below.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2600,
    location: "Paris",
    country: "France",
  },
  {
    title: "Treehouse in the Smokies",
    description: "Adventure awaits in this elevated cabin nestled in the Smoky Mountains.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1608889175773-c7b2eebf032b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1050,
    location: "Gatlinburg",
    country: "United States",
  },
  {
    title: "Icelandic Aurora Igloo",
    description: "Sleep under the Northern Lights in this cozy igloo with a view of the sky.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542317854-16671f62e85b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Reykjavik",
    country: "Iceland",
  },
  {
    title: "Floating River Cabin",
    description: "Enjoy peaceful waterside mornings in this floating cabin nestled on the river.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1533371452382-d45a9da51ad9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1150,
    location: "Amazon Basin",
    country: "Brazil",
  },
  {
    title: "Urban Micro Apartment",
    description: "Efficient and stylish, this small space packs a big punch in the heart of the city.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586105251261-72a756497a12?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 850,
    location: "Seoul",
    country: "South Korea",
  },
  {
    title: "Antarctic Ice Base",
    description: "For the ultimate adventure seeker — sleep in warmth at the edge of the world.",
    image: { filename: "listingimage",
      url: "https://images.unsplash.com/photo-1608136249131-07620ed66d56?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 5000,
    location: "McMurdo Station",
    country: "Antarctica",
  },
];


module.exports = { data: sampleListings };